[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
    \ 'colorscheme': 'powerline'
    \ }
    set laststatus=2
    set noshowmode
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
