[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
    \     'colorscheme': 'powerline',
    \     'active': {
    \         'left': [ ['mode', 'paste'], ['readonly', 'filepath', 'modified'] ],
    \     },
    \     'component_function':{
    \         'filepath': 'FilePath'
    \     },
    \ }

    function! FilePath()
        if winwidth(0) > 90
    "        return expand("%:p:~")
            return expand("%f")
        else
            return expand("%:t")
        endif
    endfunction

    set laststatus=2
    set noshowmode
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
    let g:ctrlp_clear_cache_on_exit = 0
    let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
'''
